server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: dbUrl
    username: dbUser
    password: dbPass
    initialization-mode: always
    schema:
      - classpath:sql/schema.sql
#    data:
#      - classpath:sql/data.sql
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none #update
    open-in-view: true
  mail:
    username: mailUser
    password: mailPass
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: googleClientId
            client-secret: googleSecret
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/youtube.readonly

# JWT configuration
jwt:
  secret: jwtSecret
  expirationMs: 86400000

# Default admin user
default:
  admin:
    name: defaultAdminName
    email: defaultAdminEmail
    password: defaultAdminPass

# Cloudinary settings
cloudinary:
  name: cloudinaryName
  key: cloudinaryKey
  secret: cloudinarySecret