export const LOGIN_COMPANY_SUCCESS = 'LOGIN_COMPANY_SUCCESS';
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const GET_SUBSCRIBERS = 'GET_SUBSCRIBERS';
export const CHANGE_SUBSCRIBER_STATUS = 'CHANGE_SUBSCRIBER_STATUS';
export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS';
export const GET_COMPANY_PROFILE = 'GET_COMPANY_PROFILE';
export const REDIRECTED = 'REDIRECTED';

export const YOUTUBERS_BY_SUBS = 'YOUTUBERS_BY_SUBS';
export const YOUTUBERS_LIST = 'YOUTUBERS_LIST';
export const YOUTUBERS_FILTERS = 'YOUTUBERS_FILTERS';
export const YOUTUBER_PROFILE = 'YOUTUBER_PROFILE';
export const YOUTUBER_DETAILS = 'YOUTUBER_DETAILS';
export const YOUTUBER_APPLICATIONS = 'YOUTUBER_APPLICATIONS';

export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const COMPANY_APPLICATIONS_LIST = 'COMPANY_APPLICATIONS_LIST';
export const COMPANIES_BY_RATING = 'COMPANIES_BY_RATING';
export const COMPANIES_FILTERS = 'COMPANIES_FILTERS';
export const COMPANIES_ADS = 'COMPANIES_ADS';
export const CHECK_SUBSCRIPTION = 'CHECK_SUBSCRIPTION';
export const REGISTER_REQUESTS = 'REGISTER_REQUESTS';
export const REGISTER_HISTORY = 'REGISTER_HISTORY';
export const UPDATE_REGISTER_STATUS = 'UPDATE_REGISTER_STATUS';
export const SUBSCRIBE = 'SUBSCRIBE';

export const AD_LIST = 'AD_LIST';
export const AD_COMPANY_LIST = 'AD_COMPANY_LIST';
export const AD_DETAILS = 'AD_DETAILS';
export const AD_APPLICATIONS = 'AD_APPLICATIONS';
export const AD_FILTERS = 'AD_FILTERS';
export const CREATE_AD = 'CREATE_AD';
export const BLOCK_AD = 'BLOCK_AD';
export const UNBLOCK_AD = 'UNBLOCK_AD';