export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const LOGIN_COMPANY_SUCCESS = 'LOGIN_COMPANY_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';

export const LOAD_USER_INFO = 'LOAD_USER_INFO';

export const CREATE_AD = 'CREATE_AD';